### ISSUE TITLE
12-hour clock

### ISSUE THREAD

**Issue by Adrast** [altair-viz/altair#1155]
Is there a way to change the 12-hour clock to a 24-hour clock as seen on the picture?
<img width="1086" alt="skaermbillede 2018-10-05 13 35 31" src="https://user-images.githubusercontent.com/14887881/46533106-b794b200-c8a3-11e8-8cb9-d54c8ef4c6c3.png">

**Comment by Alcampopiano** [comment]
In your x channel you could use on of the [D3 time formatting strings listed here](https://github.com/d3/d3-time-format#locale_format). 

For example

```python
.
.
.
x=alt.X('Date:T', axis=alt.Axis(format='%H'))
```

**Comment by ejain** [comment]
By setting a fixed formatting string you lose the ability to have the tick labels be smart and include dates among the times (as shown in the picture above).

**Comment by joelostblom** [comment]
@Adrast I am going through Altair issues to find those that have been resolved and can be closed. It looks to me like this issue has been solved so I am closing it, but please feel free to reopen and add a comment if there is something you don't think is resolved yet.

**Comment by ejain** [comment]
I think the issue remains: How do you control these kinds of settings, while using an automatic scale on a time axis.

**Comment by joelostblom** [comment]
Thanks for clarifying @ejain . You can achieve this via `labelExpr`:

```py
import altair as alt
from vega_datasets import data

temps = data.seattle_temps().query('date < "2010-01-05"')

time_fmt = "hours(datum.value) == 12 ? '12:00' : timeFormat(datum.value)"
alt.Chart(temps).mark_line().encode(
    alt.X('date:T', axis=alt.Axis(labelExpr=time_fmt)),
    y='temp:Q')
```

![image](https://user-images.githubusercontent.com/4560057/108950098-835bf080-761a-11eb-98c5-431d5ac8c874.png)

I believe the AM/PM is automatically determined by Vega based on your browser's locale. You can customize the locale in Altair as shown in https://github.com/altair-viz/altair/issues/505#issuecomment-608655572, but for me that only changes the language and not the AM/PM part. I am not 100% sure if it should also change the AM/PM, but feel free to open a new issue about that if you want the locale to work specifically and not use `labelExpr`.

**Comment by swapsCAPS** [comment]
FWIW For dynamic temporal axes this worked for me. Very tweakable this way, bit clunky though :sweat_smile: 
```python
fmt_obj = '{ "year": "%Y", "quarter": "%B", "month": "%B", "week": "%b %d", "date": "%a %d", "hours": "%H:%M", "minutes": "%H:%M", "seconds": ":%S", "milliseconds": ".%L" }'
time_fmt = f"timeFormat(datum.value, { fmt_obj })" 
x_axis = alt.X('time', axis=alt.Axis(labelExpr=time_fmt))
```
