### ISSUE TITLE
Tutorial AreaCharts empty plot

### ISSUE THREAD

**Issue by michaelaye** [altair-viz/altair#433]
Running `06-AreaCharts.ipynb` on python 3.6 via conda/jupyterlab/github_extension I get an empty plot in cell [4]:

![screenshot 2017-11-10 11 58 11](https://user-images.githubusercontent.com/69774/32674029-acc6b3ca-c60e-11e7-8a79-083f57a67b56.png)

**Comment by jakevdp** [comment]
Thanks. I'll investigate when I have the chance.

**Comment by gunkl** [comment]
this isn't limited scope to python 3.6 nor the tutorial charts.

i've installed altair on Windows 10 and python2.7, and centos with python2.7, and can't seem to get anything but empty charts just like the above.  I'm trying to save them out to html, or serve them with a web server, same result.  

i tried a few of the tutorials just to go backwards and found that most produce just a single circle point.

**Comment by jakevdp** [comment]
Fixed in v2

**Comment by sid-kap** [comment]
This is still happening to me on v2.0.1 (in Jupyter Lab). Is there something I can do to debug?

**Comment by jakevdp** [comment]
Do you have adblock on? Sometimes that prevents the vega-lite script from accessing data.

**Comment by jakevdp** [comment]
Otherwise, please open the javascript console and tell us if you see any errors.

**Comment by sid-kap** [comment]
Restarting jupyter notebook fixed it. Sorry for the noise!

**Comment by sid-kap** [comment]
So this is happening with me only if I turn on the JSON transformer (`alt.data_transformers.enable('json')`).
The error in the console is:
```
ERROR Data ingestion failed altair-data-55b85357-0710-42fb-b856-74a5bc29cb25.json 
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
```
However, the data in the json file looks correct (it's an array of objects). Also, I can see that it's loading the correct json URL because my Jupyter console shows
```
[I 22:40:52.808 LabApp] 302 GET /files/data-env/altair-data-55b85357-0710-42fb-b856-74a5bc29cb25.json (::1) 0.73ms
```
I am also seeing this warning in the JavaScript console:
```
The compiled spec uses Vega v3, but current version is 4.0.0-rc.2.
```
Could this be the issue? Maybe the newer version of Vega expects the JSON data to be formatted differently?

**Comment by jakevdp** [comment]
What is the content of the JSON file?

**Comment by sid-kap** [comment]
```
[{"a":"A","b":28},{"a":"B","b":55},{"a":"C","b":43},{"a":"D","b":91},{"a":"E","b":81},{"a":"F","b":53},{"a":"G","b":19},{"a":"H","b":87},{"a":"I","b":52}]
```

**Comment by sid-kap** [comment]
This is for a different example than the code I posted above, but the content is
```json
[{"a":"A","b":28},{"a":"B","b":55},{"a":"C","b":43},{"a":"D","b":91},{"a":"E","b":81},{"a":"F","b":53},{"a":"G","b":19},{"a":"H","b":87},{"a":"I","b":52}]
```

**Comment by jakevdp** [comment]
Huh... I wonder if it's some kind of file encoding issue? What platform are you on?

**Comment by sid-kap** [comment]
Linux (NixOS)

**Comment by sid-kap** [comment]
Also, this is a bit irrelevant, but why is the mimetype `application/json` rather than `application/vnd.vegalite.v2+json`? Looking at the code, I expected the latter because of the following code: 
https://github.com/altair-viz/altair/blob/eadd15b650a088c99bfbb5a871b7a06c32aa3b1c/altair/vegalite/v2/display.py#L21

**Comment by jakevdp** [comment]
The only reason that ``_repr_mimebundle_`` would return ``application/json`` is if you enable the JSON renderer using ``alt.renderers.enable('json')``. Otherwise it will be of type ``application/vnd.vegalite.v2+json``.

I can't reproduce the error you're getting, but I believe the JSON.parse error is coming from the Vega library when it tries to parse the JSON file output that is automatically created by the JSON transformer (that's what you enabled by calling ``alt.data_transformers.enable('json')``). What this does is to take your dataframe and save it to a local file with a name like ``altair-data-15cdc138-2c83-40ee-adf3-08d54587ffad.json``, and then pass this URL as a data reference. The error is occurring when Vega-Lite tries to parse that file, which is why I thought it might be an encoding issue.

**Comment by jakevdp** [comment]
What is the output of the following on your system?
```
import sys
sys.getdefaultencoding()
```

**Comment by sid-kap** [comment]
'utf-8'

**Comment by jakevdp** [comment]
Hmm... so encoding is probably not the issue then. I'm stumped.

**Comment by sid-kap** [comment]
It looks like the problem is that it's not sending the request with a cookie. Here's a screenshot from Firefox developer tools. If I copy-paste the URL into a new browser tab, it succeeds with code 200 or 304. But this one failed with 200.
![screenshot from 2018-06-06 18 31 28](https://user-images.githubusercontent.com/6425077/41070339-e1dec1b8-69b7-11e8-8e6c-9961f8325d86.png)

**Comment by sid-kap** [comment]
Ah, I understand the problem now. The response is a 302, which means it's a redirect, and it has a location header: `/login?next=%2Ffiles%2Faltair-…b-4a8c-9c0a-0917c643f369.json`.
So then Firefox sends a second request, which succeeds:
![screenshot from 2018-06-06 18 35 55](https://user-images.githubusercontent.com/6425077/41070424-758e62a6-69b8-11e8-9fa3-9e60ebbfe9ae.png)
But it's the wrong file...
![screenshot from 2018-06-06 18 36 20](https://user-images.githubusercontent.com/6425077/41070440-885eeeaa-69b8-11e8-8cea-14124b916957.png)

**Comment by sid-kap** [comment]
I suspect that this issue will be fixed if I turn off password protection in my notebook.

**Comment by jakevdp** [comment]
> I suspect that this issue will be fixed if I turn off password protection in my notebook.

Yep, I bet that's it. @ellisonbg, any thoughts on how to address the case of file access in a password-protected notebook?

**Comment by sid-kap** [comment]
As we discussed, the problem was that JupyterLab's vega renderer was not sending cookies in its XHR call to access the JSON file. I modified the JupyterLab vega renderer code and it works for me now.
I've opened a pull request here: https://github.com/jupyterlab/jupyterlab/pull/4707.
