### ISSUE TITLE
altair.vegalite.v2.api.Chart shown in Jupyter lab but not in exported files

### ISSUE THREAD

**Issue by biotemon** [altair-viz/altair#865]
This is the code:

```
plot=alt.Chart(rarefaction_df).mark_line().encode(
    x='Reads:Q',
    y='Species Counts:Q',
    color='Time_days:N',
    row='Treatment'
)
plot 
```

The plot at the Jupyter lab notebook looks perfect. 

But if I do

`plot.save("plot_rarefaction.svg")`

or

`plot.save("plot_rarefaction.html")`

The plot is basically empty and incomplete.

PS: If I do

`plot.save("plot_rarefaction.png")`

The png file is corrupted and it doesn't open. 

What can I do?

**Comment by jakevdp** [comment]
What does ``plot.to_dict()`` return?

**Comment by jakevdp** [comment]
The issue might be with spaces in your column names; I recall that coming up in the past.

**Comment by biotemon** [comment]
{'config': {'view': {'width': 400, 'height': 300}},
 'data': {'url': 'altair-data-f6ce06ff-7b4a-4824-9567-b152b9a960ef.csv',
  'format': {'type': 'csv'}},
 'mark': 'line',
 'encoding': {'color': {'type': 'nominal', 'field': 'Time_days'},
  'row': {'type': 'nominal', 'field': 'Treatment'},
  'x': {'type': 'quantitative', 'field': 'Reads'},
  'y': {'type': 'quantitative', 'field': 'Species Counts'}},
 '$schema': 'https://vega.github.io/schema/vega-lite/v2.3.0.json'}

**Comment by jakevdp** [comment]
It looks like you are using ``alt.data_transformers.enable('json')``, yes:?

Switch to ``alt.data_transformers.enable('default')`` and then all of the above will work.

**Comment by jakevdp** [comment]
That said, we fixed that issue in the most recent release. What is your ``alt.__version__``?

If it's ``2.0.0rc1`` or ``2.0.0rc2``, you should update to the ``2.0.1`` release.

**Comment by biotemon** [comment]
So....
it is `'2.0.0rc2'`

I tried:

```
#alt.data_transformers.enable('csv')
alt.renderers.enable('default')
plot_rare = alt.Chart(rarefaction_df).mark_line().encode(
    x='reads:Q',
    y='species_counts:Q',
    color='time_days:N',
    row='treatment'
)
#plot_rare.save("plot_rarefaction.html")
plot_rare.to_dict()
```

This is the output

```
{'config': {'view': {'width': 400, 'height': 300}},
 'data': {'url': 'altair-data-79d574d6-30d6-4e59-b408-31c3454af544.csv',
  'format': {'type': 'csv'}},
 'mark': 'line',
 'encoding': {'color': {'type': 'nominal', 'field': 'time_days'},
  'row': {'type': 'nominal', 'field': 'treatment'},
  'x': {'type': 'quantitative', 'field': 'reads'},
  'y': {'type': 'quantitative', 'field': 'species_counts'}},
 '$schema': 'https://vega.github.io/schema/vega-lite/v2.3.0.json'}
```

The error still persists... I am trying to update to the most recent release.

**Comment by jakevdp** [comment]
Yes, please update to the most recent release.

**Comment by biotemon** [comment]
It worked. 
Thank you very much!
